### ISSUE TITLE
Add E2E testing

### ISSUE THREAD

**Issue by vanGalilea** [vanGalilea/react-native-testing#32]
With Detox/Appium?

**Comment by alextorres94** [comment]
Have you finally decided on one of them? I'm interested in your opinion ☺️

**Comment by vanGalilea** [comment]
@alextorres94 Detox has always been my fav. due to numerous reasons. Yet both have pros and cons.

**Comment by alextorres94** [comment]
FYI @vanGalilea I have finally decided to use Maestro https://github.com/mobile-dev-inc/maestro

**Comment by vanGalilea** [comment]
@alextorres94 yep been using Maestro for a while. It seems to gain some traction

**Comment by vanGalilea** [comment]
Great CI examples:
https://github.com/callstack/react-native-pager-view/pull/716
https://github.com/stripe/stripe-react-native/blob/master/.github/workflows/e2e-tests.yml
