### ISSUE TITLE
FEATURE:  Modal Test

### ISSUE THREAD

**Issue by kblankenship1989** [vanGalilea/react-native-testing#6]
If possible, can you add a sample test for using a react-native modal.  I would like to test the modal being closed at the start, then clicking a button opens it before going further and I cannot figure out how to do this.

**Comment by vanGalilea** [comment]
You meant this modal? https://reactnative.dev/docs/modal

**Comment by kblankenship1989** [comment]
> You meant this modal? https://reactnative.dev/docs/modal

Yes that exactly.  I have implemented one of these but am new to `@testing-library/react-native` and can't figure out proper testing for this.

My test case is:

 - When app opens, modal is closed.
 - Click the find the "Add new" button and modal should appear
 - Find test field in modal and enter value.
 - click create.  Modal should disappear

The problem I have is the modal is always in the tree (doing `getByText({ModalHeaderText})` is always true).  How can I use this library to assert the modal is open / closed properly?

**Comment by vanGalilea** [comment]
Correct, there is away to solve this by, mocking the modal and making sure that when the modal is closed, it's children aren't gonna show in the tree.

You can something similar to mockComponent from react-native/jest/mockComponent.

I'm working on this example and we'll also make a pull request for the library, when I'll figure everything out.

**Comment by vanGalilea** [comment]
@kblankenship1989 I just updated the repo with a new example testing a modal.
 https://github.com/vanGalilea/react-native-testing/blob/master/__tests__/Modal.test.tsx
I'm closing this issue

**Comment by olawalethefirst** [comment]
> @kblankenship1989 I just updated the repo with a new example testing a modal.
> https://github.com/vanGalilea/react-native-testing/blob/master/__tests__/Modal.test.tsx
> I'm closing this issue

Please, I'm curious as to if the fix for the react-native's bug that constantly keeps a Modal and its children constantly in the test tree works for [react-native-modal](https://github.com/react-native-modal/react-native-modal) as well

**Comment by yakupdurmus** [comment]
> @kblankenship1989 I just updated the repo with a new example testing a modal. https://github.com/vanGalilea/react-native-testing/blob/master/__tests__/Modal.test.tsx I'm closing this issue

I don't have a button to close the modal (Hide Modal etc.). I close the Modal by pressing the outside. How can I write a test for this?

My modal like this. I want to close when I press the outside on Jest Test
![image](https://github.com/vanGalilea/react-native-testing/assets/19963665/181e6a6c-4cf5-42f6-85a0-9c0913e991d4)
