### ISSUE TITLE
msw + maestro

### ISSUE THREAD

**Issue by hackdie** [vanGalilea/react-native-testing#65]
Great examples on how to get into the testing world 💪🏼 , i just have a question, would it be possible (and even make sense) to use msw with maestro to decouple  the server and confirm that views are displayed as expected

**Comment by vanGalilea** [comment]
Hey @hackdie it might make some sense in some cases. However, I  would suggest you to use your real backend's APIs (acceptance/development environment) when E2E testing.

If you wish, you may still choose to run an MSW API instance prior to starting the E2E tests.
